DROP TABLE CLIENTE IF EXISTS ;
DROP TABLE PRODUCTO IF EXISTS ;
DROP TABLE COMPRA IF EXISTS ;
DROP TABLE VENTA IF EXISTS ;

CREATE TABLE Cliente (
clienteId INTEGER NOT NULL,
dni INTEGER NOT NULL,
apellido VARCHAR(150) NOT NULL,
nombre VARCHAR(150) NOT NULL,
PRIMARY KEY (clienteId)
);

CREATE TABLE Producto (
productoId INTEGER NOT NULL,
codigo INTEGER NOT NULL,
precio DECIMAL NOT NULL,
cantitdadProducto INTEGER NOT NULL,
descripcion VARCHAR(150) NOT NULL,
PRIMARY KEY (productoId)
);

CREATE TABLE Compra (
compraId INTEGER NOT NULL,
clienteId INTEGER NOT NULL,
productoId INTEGER NOT NULL,
cantidadCompra INTEGER NOT NULL,
fecha DATETIME NOT NULL,
total DECIMAL NOT NULL,
PRIMARY KEY (compraId),
FOREIGN KEY (clienteId) REFERENCES Cliente (clienteId),
FOREIGN KEY (productoId) REFERENCES Producto (productoId)
);

CREATE TABLE Venta (
ventaId INTEGER NOT NULL,
clienteId INTEGER NOT NULL,
compraId INTEGER NOT NULL,
totalVenta DECIMAL NOT NULL,
PRIMARY KEY (ventaId),
FOREIGN KEY (compraId) REFERENCES Compra (compraId)
);